name: Check if links are valid

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  link-check:
    name: "Check if links are valid"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: Run linkspector
        uses: umbrelladocs/action-linkspector@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          fail_on_error: true
